projects:
  testappabhishek:
    schemaPath: amplify/backend/api/testappabhishek/build/schema.graphql
    includes:
      - mutation
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
